#spring.profiles.active=dev

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/primes
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  rabbitmq:
    host: localhost
    port: 4008
    username: guest
    password: guest

server:
  port: 8085

debug: on

